### PR TITLE
add operator defaultsTo

### PR DESCRIPTION
**Pull request by b1conrad**
@farskipper would you be so kind as to check out this new operator and merge if it looks okay to you

### CODE REVIEW

**Comment by windley** [comment]
I don't have any comments on this specifically. Looks good. 

It does make me wonder however, about how we are using console.log() and how we might later implement pico logging. 

Should we create our own logging primitive that uses console.log() but allows us, later, to change it to support pico logging as well without having to find and change all the places we've used console.log()?

**Comment by b1conrad** [comment]
Good idea! AFAIK one other operator, klog, uses it in this manner.

**Comment by windley** [comment]
There are lots of error conditions for operators that also log information.

**Comment by b1conrad** [comment]
Looks like it's okay as written. As I run the node.js CLI these results show:

> require('lodash').size(null)
> 0
> require('lodash').size(undefined)
> 0
> require('lodash').size(0)
> 0
> require('lodash').size(50)
> 0
> require('lodash').size([])
> 0
> require('lodash').size({})
> 0

**Comment by alexkolson** [comment]
[winston](https://github.com/winstonjs/winston) is a pretty crazy awesome logging utility and gives you a bunch of power as to exactly what mechanism is used write the logs. For example, you could swap console.log for pico logging later down the road without having to pull your hair out. 😄 

Getting concrete:

``` js
// Oh hey for now we're using console....
const winston = require('winston');
winston.info('doing some cool stuff with picos!');

// Then later we have awesome pico logging goodness
const winston = require('winston');
const picoLoggingTransport = require('pico-logging-awesomeness');
winston.add(picoLoggingTransport, options);
// We don't want to be using console anymore...
winston.remove(winston.transports.Console);
```

Of course, winston is far from the only game in town, but using something like this or even rolling your own that has similar functionality before `console.log` is littered throughout the codebase of the krl engine would be cool.

**Comment by windley** [comment]
Thanks @alexkolson!

**Comment by farskipper** [comment]
Cool! I just added an EventEmitter to the stdlib. (`stdlib.emitter`) This way we can pass logging, warnings, errors etc. on to the pico-engine. The engine can then pass the events into "KRL land" where it can be logged and/or handled.

**Pull request merged**
