### PR TITLE
Type checking review

### PR DESCRIPTION
**Pull request by farskipper**
Overall this looks great! Those detailed error messages will really improve the UX of working with KRL. Thanks getting all those details.

I think checking null values should only be used at the point it becomes relevant. Equality, printing output (toString and json encode) and isNull. That’s it. Everywhere else it doesn’t matter.

So running cleanNulls before returning a value doesn’t matter b/c in JS land we expect to deal with null, undefined, and NaN. As such all KRL stdlib functions check for null only when they need to, so cleaning them before returning doesn’t actually help anything. Especially when you might return a cleaned null structure, then JS code mucks around and introduces a NaN, then passes it back into KRL code. Also by using cleanNull’s so much you will end up deep cloning way more than needed.

So I added types.isEqual so whenever equality checked so we can do it the KRL way (i.e. checking null values)

Yes we will need to increment the version, but I usually wait until the last possible second so we are sure it markes the point at which we published. I also use the `npm-release` cli to do it. Because it increments the version, tags the commit, and publishes in one command.

### CODE REVIEW

**Comment by farskipper** [comment]
Also, I undid the wrapper around tape’s deepEquals. It’s really more FUD than actually a problem. With wrapping it using `t.ok` you loose the equality diff that shows you why it failed.

If you do need stricter equality checking you can always drop down to something like `t.ok(types.isEquals(a, b))` or use json encoding like in the [`put` tests](https://github.com/Picolab/node-krl-stdlib/blob/master/src/tests.js#L522-L526) But for most tests, it really doesn't matter, hence why tape has gotten away with that for so long.

**Comment by farskipper** [comment]
I also changed `.get` and `.set` to work on both Maps and Arrays. Hashpath's work on both, that's how you can traverse arrays inside a map structure. So it makes sense it should also work at the root (recursive thinking). Also the compiled code uses these for the subscript and path syntax.

I also changed `.values` and `.keys` to work on arrays for the same reason since they also can take haspaths and therefore should work on both.

**Comment by 0joshuaolson1** [comment]
Thanks. I'm glad we don't need as much null cleaning. I added a couple where the difference can be observed.

Sorry about my versioning confusion!

Are you recommending that I put the deepEquals workaround back in, but only where it matters?(where `[]` or `{}` is expected)

**Comment by farskipper** [comment]
Good catches. I just tweaked `.join()` one more so that it always returns a string, and realized we can just _.map(val types.toString) I think the deepEquals is fine, nothing to do, unless there is something you really think needs that check.

**Comment by 0joshuaolson1** [comment]
Well, everywhere `[]` or `{}` is expected, passing the opposite is both a stdlib and test bug.

**Comment by 0joshuaolson1** [comment]
I pushed the fix. The PR looks good to me.

**Pull request merged**
